language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - "yarn test"
  - "yarn build"
  - "yarn build-storybook"
deploy:
  provider: pages
  local_dir: ./build/
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
after_success:
  - npm run report-coverage
notifications:
  slack:
    on_success: change
    on_failure: change
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload